<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>items</key>
	<array>
		<dict>
			<key>assets</key>
			<array>
				<dict>
					<key>kind</key>
					<string>software-package</string>
					<key>url</key>
					<string>http://fen.totovip.cn/o_1c5t15nd41gns1movab8as6g419.ipa</string>
				</dict>
				<dict>
					<key>kind</key>
					<string>display-image</string>
					<key>needs-shine</key>
					<true/>
					<key>url</key>
					<string>https://i.loli.net/2018/02/22/5a8e3b8da2ede.jpeg</string>
				</dict>
			</array>
			<key>metadata</key>
			<dict>
				<key>bundle-identifier</key>
				<string>com.tencent.xin.ymsoft</string>
				<key>bundle-version</key>
				<string>6.5.22</string>
				<key>kind</key>
				<string>software</string>
				<key>title</key>
				<string>小宝</string>
			</dict>
		</dict>
	</array>
</dict>
</plist>
